from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any

from .models import GeneratedBundle, WorkspaceResult, utc_now_iso
from .safety import safe_join, slugify_project_name


class WorkspaceManager:
    """Creates safe project workspaces.

    This manager never deletes files and never executes shell commands.
    Existing file names are preserved by writing versioned alternatives.
    """

    def __init__(self, root_dir: Path) -> None:
        self.root_dir = root_dir.expanduser()
        self.root_dir.mkdir(parents=True, exist_ok=True)

    def preview_workspace(self, project_name: str) -> list[str]:
        slug = slugify_project_name(project_name)
        return [
            f"{slug}/README.md",
            f"{slug}/notes/project_notes.md",
            f"{slug}/notes/design_signal.md",
            f"{slug}/notes/project_brief.md",
            f"{slug}/tasks/tasks.json",
            f"{slug}/logs/activity_log.md",
            f"{slug}/src/.gitkeep",
            f"{slug}/assets/.gitkeep",
            f"{slug}/exports/.gitkeep",
            f"{slug}/manifest.json",
        ]

    def create_workspace(self, bundle: GeneratedBundle) -> WorkspaceResult:
        slug = bundle.slug or slugify_project_name(bundle.project_name)
        workspace = safe_join(self.root_dir, slug)
        workspace.mkdir(parents=True, exist_ok=True)

        folders = [
            "notes",
            "tasks",
            "logs",
            "src",
            "assets",
            "exports",
        ]

        for folder in folders:
            safe_join(workspace, folder).mkdir(parents=True, exist_ok=True)

        manifest = {
            "project_name": bundle.project_name,
            "slug": slug,
            "created_at": utc_now_iso(),
            "generator": "Lexi local template engine",
            "metadata": bundle.metadata,
        }

        files: dict[str, str] = {
            "README.md": self._readme(bundle),
            "notes/project_notes.md": bundle.note + "\n",
            "notes/design_signal.md": bundle.signal + "\n",
            "notes/project_brief.md": bundle.brief + "\n",
            "tasks/tasks.json": json.dumps(bundle.tasks, indent=2, ensure_ascii=False) + "\n",
            "logs/activity_log.md": f"# Activity Log — {bundle.project_name}\n\n- {utc_now_iso()} Workspace generated.\n",
            "src/.gitkeep": "",
            "assets/.gitkeep": "",
            "exports/.gitkeep": "",
            "manifest.json": json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        }

        written: list[str] = []
        skipped: list[str] = []

        for relative_path, content in files.items():
            target = safe_join(workspace, relative_path)
            written_path = self._write_versioned(target, content)
            if written_path == target:
                written.append(str(written_path))
            else:
                written.append(str(written_path))
                skipped.append(str(target))

        return WorkspaceResult(
            workspace_path=str(workspace),
            written_files=written,
            skipped_files=skipped,
            message=f"Workspace ready at {workspace}",
        )

    def _write_versioned(self, path: Path, content: str) -> Path:
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            return path

        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        versioned = path.with_name(f"{path.stem}.{stamp}{path.suffix}")
        versioned.write_text(content, encoding="utf-8")
        return versioned

    def _readme(self, bundle: GeneratedBundle) -> str:
        return f"""# {bundle.project_name}

Generated by Lexi.AI Desktop Companion.

## What this workspace contains

- `notes/project_notes.md` — generated project notes
- `notes/design_signal.md` — generated design signal
- `notes/project_brief.md` — structured project brief
- `tasks/tasks.json` — generated task list
- `logs/activity_log.md` — workspace activity log
- `src/` — source code area
- `assets/` — asset area
- `exports/` — generated/exported output area

## Safety model

This workspace was created by a local template generator. Existing files are not deleted or overwritten; versioned files are created instead.

## Next step

Open `notes/project_brief.md` and begin implementation from the generated task list.
"""
