"""Blueprint Forge — multi-format Brand Blueprint + starter code generator.

Outputs inspectable Markdown, JSON, HTML, and optional starter code modules
for review. No remote side effects. Speculative physics stays out of scope.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from .artifacts import (
    WORKSPACE,
    ensure_dirs,
    simple_html_page,
    slugify,
    utc_stamp,
    write_bundle,
    write_json,
    write_text,
)
from .code_generator import generate_brand_blueprint
from .eval_log import log_evaluation


def forge_blueprint(
    name: str,
    *,
    vibe: str = "",
    audience: str = "",
    offer: str = "",
    include_code: bool = True,
    memory=None,
) -> dict[str, Any]:
    """Forge a full Brand Blueprint Pack (+ optional starter code files)."""
    ensure_dirs()
    pack = generate_brand_blueprint(
        name,
        vibe=vibe,
        audience=audience,
        offer=offer,
        memory=memory,
    )
    data = pack["data"]
    paths: dict[str, str] = dict(pack["paths"])
    code_paths: dict[str, str] = {}

    if include_code:
        code_paths = _write_starter_code(data)
        paths.update(code_paths)

    # Forge manifest for dashboard / delivery
    stamp = utc_stamp()
    slug = slugify(data["title"])
    manifest = {
        "forge": "Blueprint Forge",
        "version": "1.0.0",
        "title": data["title"],
        "brand_name": data["brand_name"],
        "price_starting_usd": data["price_starting_usd"],
        "cta": data["cta"],
        "paths": paths,
        "includes_code": include_code,
        "review_gate": [
            "Customer reviews name/slogan/bio",
            "Confirm vibe and audience",
            "Export HTML or PDF for delivery",
            "Starter code is optional template only",
        ],
        "boundaries": data["boundaries"],
        "summary": f"Blueprint Forge pack for {data['brand_name']}",
    }
    manifest_path = WORKSPACE / "deliverables" / "blueprints" / f"{stamp}-{slug}-forge-manifest.json"
    write_json(manifest_path, manifest)
    paths["forge_manifest"] = str(manifest_path)

    if memory is not None:
        memory.save_deliverable(
            "blueprint_forge",
            data["title"],
            paths,
            meta={"brand_name": data["brand_name"], "include_code": include_code},
        )
        log_evaluation(
            memory,
            category="deliverable",
            subject=f"blueprint_forge:{data['brand_name']}",
            notes="Generated multi-format brand pack via Blueprint Forge",
            score=0.9,
            payload={"paths": paths, "include_code": include_code},
        )

    return {
        "title": data["title"],
        "brand_name": data["brand_name"],
        "paths": paths,
        "data": data,
        "manifest": manifest,
        "code_paths": code_paths,
    }


def _write_starter_code(data: dict[str, Any]) -> dict[str, str]:
    """Generate reviewable starter code templates for the brand pack."""
    ensure_dirs()
    stamp = utc_stamp()
    slug = slugify(data["brand_name"])
    code_dir = WORKSPACE / "deliverables" / "blueprints" / "code" / f"{stamp}-{slug}"
    code_dir.mkdir(parents=True, exist_ok=True)

    # Python data module
    py = f'''"""Starter brand pack module for {data["brand_name"]}.
Generated by Drewskii.Engine Blueprint Forge — review before production use.
"""
from __future__ import annotations

BRAND = {{
    "name": {data["brand_name"]!r},
    "title": {data["title"]!r},
    "slogan": {data["slogan"]!r},
    "bio": {data["bio"]!r},
    "vibe": {data["vibe"]!r},
    "audience": {data["audience"]!r},
    "offer": {data["offer"]!r},
    "price_starting_usd": {data["price_starting_usd"]},
    "cta": {data["cta"]!r},
    "image_prompts": {data["image_prompts"]!r},
    "ad_copy": {data["ad_copy"]!r},
    "concept_sheet": {data["concept_sheet"]!r},
}}


def as_markdown() -> str:
    lines = [
        f"# {{BRAND['name']}}",
        "",
        f"**Slogan:** {{BRAND['slogan']}}",
        "",
        BRAND["bio"],
        "",
        f"**CTA:** {{BRAND['cta']}} · from ${{BRAND['price_starting_usd']}}",
    ]
    return "\\n".join(lines) + "\\n"


if __name__ == "__main__":
    print(as_markdown())
'''
    py_path = write_text(code_dir / "brand_pack.py", py)

    # Minimal landing snippet (static)
    landing = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{data["brand_name"]} · Blueprint Landing</title>
  <style>
    body {{ margin:0; font-family:system-ui,sans-serif; background:#050607; color:#e8e6dc; }}
    .wrap {{ max-width:720px; margin:0 auto; padding:48px 20px; }}
    .badge {{ font:11px ui-monospace,monospace; letter-spacing:.14em; color:#c8ff35; }}
    h1 {{ font-size:42px; letter-spacing:-.04em; margin:12px 0; }}
    .slogan {{ color:#7b5cff; font-size:18px; }}
    .cta {{
      display:inline-block; margin-top:24px; background:#c8ff35; color:#111;
      padding:14px 18px; border-radius:10px; font-weight:700; text-decoration:none;
      font:12px ui-monospace,monospace; letter-spacing:.1em;
    }}
    p {{ line-height:1.6; color:#aeb3ac; }}
    footer {{ margin-top:40px; font:11px ui-monospace,monospace; color:#8b948c; }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="badge">BLUEPRINT FORGE · STARTER LANDING</div>
    <h1>{data["brand_name"]}</h1>
    <p class="slogan">{data["slogan"]}</p>
    <p>{data["bio"]}</p>
    <a class="cta" href="#">{data["cta"]} · FROM ${data["price_starting_usd"]}</a>
    <footer>Template only · edit before customer publish · Drewskii.Engine</footer>
  </div>
</body>
</html>
"""
    html_path = write_text(code_dir / "landing.html", landing)

    # README for the code folder
    readme = f"""# Blueprint Forge Code — {data["brand_name"]}

Generated starter templates for review.

## Files
- `brand_pack.py` — structured brand data module
- `landing.html` — static landing snippet
- Parent pack: MD / JSON / HTML deliverables one level up

## Use
```bash
python3 brand_pack.py
open landing.html
```

## Notes
- Templates only — not auto-deployed
- No secrets, no remote calls
- Review before customer delivery
"""
    readme_path = write_text(code_dir / "README.md", readme)

    return {
        "code_python": str(py_path),
        "code_landing": str(html_path),
        "code_readme": str(readme_path),
        "code_dir": str(code_dir),
    }
