"""Blueprint Forge — multi-format Brand Blueprint + starter code generator.

Outputs inspectable Markdown, JSON, HTML, and optional starter code modules
for review. No remote side effects. Speculative physics stays out of scope.
"""
from __future__ import annotations

import json
import zipfile
from pathlib import Path
from typing import Any

from .artifacts import (
    WORKSPACE,
    ensure_dirs,
    simple_html_page,
    slugify,
    utc_stamp,
    write_bundle,
    write_json,
    write_text,
)
from .code_generator import generate_brand_blueprint
from .eval_log import log_evaluation


def forge_blueprint(
    name: str,
    *,
    vibe: str = "",
    audience: str = "",
    offer: str = "",
    include_code: bool = True,
    memory=None,
) -> dict[str, Any]:
    """Forge a full Brand Blueprint Pack (+ optional starter code files)."""
    ensure_dirs()
    pack = generate_brand_blueprint(
        name,
        vibe=vibe,
        audience=audience,
        offer=offer,
        memory=memory,
    )
    data = pack["data"]
    paths: dict[str, str] = dict(pack["paths"])
    code_paths: dict[str, str] = {}

    if include_code:
        code_paths = _write_starter_code(data)
        paths.update(code_paths)

    # Forge manifest for dashboard / delivery
    stamp = utc_stamp()
    slug = slugify(data["title"])
    manifest = {
        "forge": "Blueprint Forge",
        "version": "1.0.0",
        "title": data["title"],
        "brand_name": data["brand_name"],
        "price_starting_usd": data["price_starting_usd"],
        "cta": data["cta"],
        "paths": paths,
        "includes_code": include_code,
        "review_gate": [
            "Customer reviews name/slogan/bio",
            "Confirm vibe and audience",
            "Export HTML or PDF for delivery",
            "Starter code is optional template only",
        ],
        "boundaries": data["boundaries"],
        "summary": f"Blueprint Forge pack for {data['brand_name']}",
    }
    manifest_path = WORKSPACE / "deliverables" / "blueprints" / f"{stamp}-{slug}-forge-manifest.json"
    write_json(manifest_path, manifest)
    paths["forge_manifest"] = str(manifest_path)

    if memory is not None:
        memory.save_deliverable(
            "blueprint_forge",
            data["title"],
            paths,
            meta={"brand_name": data["brand_name"], "include_code": include_code},
        )
        log_evaluation(
            memory,
            category="deliverable",
            subject=f"blueprint_forge:{data['brand_name']}",
            notes="Generated multi-format brand pack via Blueprint Forge",
            score=0.9,
            payload={"paths": paths, "include_code": include_code},
        )

    # Customer-ready ZIP (Stage-1 → Stage-2 export action)
    zip_path = _export_pack_zip(data["brand_name"], paths, data)
    paths["zip"] = str(zip_path)
    manifest["paths"] = paths
    write_json(manifest_path, manifest)

    return {
        "title": data["title"],
        "brand_name": data["brand_name"],
        "paths": paths,
        "data": data,
        "manifest": manifest,
        "code_paths": code_paths,
        "zip": str(zip_path),
    }


def _export_pack_zip(
    brand_name: str,
    paths: dict[str, str],
    data: dict[str, Any],
) -> Path:
    """Zip customer-facing artifacts into one deliverable package."""
    ensure_dirs()
    stamp = utc_stamp()
    slug = slugify(brand_name)
    out_dir = WORKSPACE / "deliverables" / "blueprints" / "packages"
    out_dir.mkdir(parents=True, exist_ok=True)
    zip_path = out_dir / f"{stamp}-{slug}-brand-pack.zip"

    # Prefer stable customer files; skip huge/irrelevant paths
    prefer_keys = (
        "markdown",
        "json",
        "html",
        "forge_manifest",
        "code_python",
        "code_landing",
        "code_readme",
    )
    readme = (
        f"# {brand_name} — Brand Blueprint Pack\n\n"
        f"Price point: starting ${data.get('price_starting_usd', 50)}\n"
        f"CTA: {data.get('cta', 'BLUEPRINT')}\n\n"
        "## Contents\n"
        "- project_brief / markdown pack\n"
        "- pack.json (structured)\n"
        "- pack.html (customer view)\n"
        "- optional starter code (brand_pack.py, landing.html)\n\n"
        "## Review\n"
        "Confirm name, vibe, audience, and offer before client delivery.\n"
        "Generated by Lexi-9-Omega / Drewskii.Engine Blueprint Forge (local-first).\n"
    )
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("README.md", readme)
        zf.writestr("pack_summary.json", json.dumps({
            "brand_name": data.get("brand_name"),
            "slogan": data.get("slogan"),
            "price_starting_usd": data.get("price_starting_usd"),
            "cta": data.get("cta"),
            "audience": data.get("audience"),
            "offer": data.get("offer"),
        }, indent=2, ensure_ascii=True))
        for key in prefer_keys:
            p = paths.get(key)
            if not p:
                continue
            src = Path(p)
            if not src.is_file():
                continue
            # Flatten names for customer clarity
            if key == "markdown":
                arc = "brand_pack.md"
            elif key == "json":
                arc = "brand_pack.json"
            elif key == "html":
                arc = "brand_pack.html"
            elif key == "forge_manifest":
                arc = "forge_manifest.json"
            elif key == "code_python":
                arc = "code/brand_pack.py"
            elif key == "code_landing":
                arc = "code/landing.html"
            elif key == "code_readme":
                arc = "code/README.md"
            else:
                arc = src.name
            zf.write(src, arcname=arc)
    return zip_path


def export_existing_pack_zip(paths: dict[str, str], brand_name: str = "Brand Pack") -> Path:
    """Re-zip an existing pack paths dict (for stack export command)."""
    data = {"brand_name": brand_name, "price_starting_usd": 50, "cta": "BLUEPRINT"}
    # try load json pack if present
    jp = paths.get("json")
    if jp and Path(jp).is_file():
        try:
            data = json.loads(Path(jp).read_text(encoding="utf-8"))
            brand_name = data.get("brand_name") or brand_name
        except json.JSONDecodeError:
            pass
    return _export_pack_zip(brand_name, paths, data)


def _write_starter_code(data: dict[str, Any]) -> dict[str, str]:
    """Generate reviewable starter code templates for the brand pack."""
    ensure_dirs()
    stamp = utc_stamp()
    slug = slugify(data["brand_name"])
    code_dir = WORKSPACE / "deliverables" / "blueprints" / "code" / f"{stamp}-{slug}"
    code_dir.mkdir(parents=True, exist_ok=True)

    # Python data module
    py = f'''"""Starter brand pack module for {data["brand_name"]}.
Generated by Drewskii.Engine Blueprint Forge — review before production use.
"""
from __future__ import annotations

BRAND = {{
    "name": {data["brand_name"]!r},
    "title": {data["title"]!r},
    "slogan": {data["slogan"]!r},
    "bio": {data["bio"]!r},
    "vibe": {data["vibe"]!r},
    "audience": {data["audience"]!r},
    "offer": {data["offer"]!r},
    "price_starting_usd": {data["price_starting_usd"]},
    "cta": {data["cta"]!r},
    "image_prompts": {data["image_prompts"]!r},
    "ad_copy": {data["ad_copy"]!r},
    "concept_sheet": {data["concept_sheet"]!r},
}}


def as_markdown() -> str:
    lines = [
        f"# {{BRAND['name']}}",
        "",
        f"**Slogan:** {{BRAND['slogan']}}",
        "",
        BRAND["bio"],
        "",
        f"**CTA:** {{BRAND['cta']}} · from ${{BRAND['price_starting_usd']}}",
    ]
    return "\\n".join(lines) + "\\n"


if __name__ == "__main__":
    print(as_markdown())
'''
    py_path = write_text(code_dir / "brand_pack.py", py)

    # Minimal landing snippet (static)
    landing = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{data["brand_name"]} · Blueprint Landing</title>
  <style>
    body {{ margin:0; font-family:system-ui,sans-serif; background:#050607; color:#e8e6dc; }}
    .wrap {{ max-width:720px; margin:0 auto; padding:48px 20px; }}
    .badge {{ font:11px ui-monospace,monospace; letter-spacing:.14em; color:#c8ff35; }}
    h1 {{ font-size:42px; letter-spacing:-.04em; margin:12px 0; }}
    .slogan {{ color:#7b5cff; font-size:18px; }}
    .cta {{
      display:inline-block; margin-top:24px; background:#c8ff35; color:#111;
      padding:14px 18px; border-radius:10px; font-weight:700; text-decoration:none;
      font:12px ui-monospace,monospace; letter-spacing:.1em;
    }}
    p {{ line-height:1.6; color:#aeb3ac; }}
    footer {{ margin-top:40px; font:11px ui-monospace,monospace; color:#8b948c; }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="badge">BLUEPRINT FORGE · STARTER LANDING</div>
    <h1>{data["brand_name"]}</h1>
    <p class="slogan">{data["slogan"]}</p>
    <p>{data["bio"]}</p>
    <a class="cta" href="#">{data["cta"]} · FROM ${data["price_starting_usd"]}</a>
    <footer>Template only · edit before customer publish · Drewskii.Engine</footer>
  </div>
</body>
</html>
"""
    html_path = write_text(code_dir / "landing.html", landing)

    # README for the code folder
    readme = f"""# Blueprint Forge Code — {data["brand_name"]}

Generated starter templates for review.

## Files
- `brand_pack.py` — structured brand data module
- `landing.html` — static landing snippet
- Parent pack: MD / JSON / HTML deliverables one level up

## Use
```bash
python3 brand_pack.py
open landing.html
```

## Notes
- Templates only — not auto-deployed
- No secrets, no remote calls
- Review before customer delivery
"""
    readme_path = write_text(code_dir / "README.md", readme)

    return {
        "code_python": str(py_path),
        "code_landing": str(html_path),
        "code_readme": str(readme_path),
        "code_dir": str(code_dir),
    }
